import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  Archive,
  AtSign,
  Bell,
  Bike,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Calendar,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronUp,
  Chrome,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Code,
  Columns,
  Compass,
  Copy,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Gamepad2,
  Github,
  Gitlab,
  Globe,
  Grid,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Home,
  Image,
  Info,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  MoreVertical,
  Music,
  Package,
  Palette,
  Pause,
  Percent,
  Phone,
  Plane,
  Play,
  Plus,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Ship,
  ShoppingCart,
  Sidebar,
  Square,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Train,
  Trash2,
  Triangle,
  Truck,
  Type,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Wifi,
  Wind,
  X,
  Zap,
} from 'lucide-react';

export const commonLucideIconNames = [
  'Star', 'Heart', 'Bookmark', 'Flag', 'Tag', 'Hash',
  'Home', 'User', 'Users', 'Settings', 'Bell', 'Mail',
  'Calendar', 'Clock', 'MapPin', 'Phone', 'Camera', 'Image',
  'Folder', 'File', 'Archive', 'Trash2', 'Download', 'Upload',
  'Search', 'Filter', 'Menu', 'MoreVertical', 'ChevronDown', 'ChevronUp',
  'Plus', 'Minus', 'X', 'Check', 'AlertCircle', 'Info',
  'Edit', 'Copy', 'Share', 'Link', 'ExternalLink', 'Lock',
  'Code', 'Terminal', 'Database', 'Server', 'Cloud', 'Wifi',
  'ShoppingCart', 'CreditCard', 'Package', 'Truck', 'Store',
  'Music', 'Play', 'Pause', 'Volume2', 'Headphones', 'Mic',
  'Book', 'BookOpen', 'FileText', 'Highlighter', 'Type',
  'Layout', 'Grid', 'List', 'Columns', 'Sidebar', 'Layers',
  'Circle', 'Square', 'Triangle', 'Hexagon', 'Zap', 'Target',
  'Rocket', 'Plane', 'Car', 'Bike', 'Ship', 'Train',
  'Moon', 'Sun', 'CloudRain', 'CloudSnow', 'Wind', 'Thermometer',
  'Github', 'Gitlab', 'Chrome',
  'MessageSquare', 'MessageCircle', 'Send', 'AtSign', 'Percent',
  'Palette', 'Gamepad2', 'Bot', 'Compass', 'Globe', 'Video',
] as const;

const iconRegistry = {
  AlertCircle,
  Archive,
  AtSign,
  Bell,
  Bike,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Calendar,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronUp,
  Chrome,
  Circle,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Code,
  Columns,
  Compass,
  Copy,
  CreditCard,
  Database,
  Download,
  Edit,
  ExternalLink,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Gamepad2,
  Github,
  Gitlab,
  Globe,
  Grid,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Home,
  Image,
  Info,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  MoreVertical,
  Music,
  Package,
  Palette,
  Pause,
  Percent,
  Phone,
  Plane,
  Play,
  Plus,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Ship,
  ShoppingCart,
  Sidebar,
  Square,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Train,
  Trash2,
  Triangle,
  Truck,
  Type,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Wifi,
  Wind,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

const kebabToPascal = (kebabName: string): string => {
  return kebabName
    .split('-')
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
};

export const normalizeLucideIconName = (rawName: string): keyof typeof iconRegistry | '' => {
  const name = rawName.trim();
  if (!name) return '';

  const candidates = [
    name,
    name.includes('-') ? kebabToPascal(name) : name,
    name.charAt(0).toUpperCase() + name.slice(1),
  ];

  for (const candidate of candidates) {
    if (candidate in iconRegistry) {
      return candidate as keyof typeof iconRegistry;
    }
  }

  return '';
};

export const resolveLucideIcon = (rawName: string): LucideIcon | null => {
  const normalizedName = normalizeLucideIconName(rawName);
  return normalizedName ? iconRegistry[normalizedName] : null;
};

export const fallbackIcon = Link;
