import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  Accessibility,
  Activity,
  Airplay,
  AlarmClock,
  Album,
  AppWindow,
  Apple,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  Banknote,
  Barcode,
  BarChart3,
  Battery,
  Bell,
  BellRing,
  Bike,
  Blocks,
  Bluetooth,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronUp,
  Chrome,
  Circle,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudRain,
  CloudSnow,
  CloudUpload,
  Code,
  Cog,
  Columns,
  Command,
  Compass,
  Copy,
  CreditCard,
  Cpu,
  Crown,
  Database,
  Diamond,
  DollarSign,
  Download,
  Dumbbell,
  Earth,
  Edit,
  Ellipsis,
  Eye,
  EyeOff,
  ExternalLink,
  Figma,
  File,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Folder,
  Gamepad2,
  Gauge,
  Github,
  Gitlab,
  Gift,
  Globe,
  GraduationCap,
  Grid,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Home,
  Image,
  Inbox,
  Info,
  Landmark,
  Languages,
  Layers,
  Layout,
  Laptop,
  Laugh,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  MousePointer,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Pause,
  Percent,
  PenTool,
  Phone,
  Plane,
  Play,
  Plug,
  Plus,
  Presentation,
  Projector,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  Rocket,
  RotateCcw,
  Route,
  Router,
  Rss,
  Scan,
  School,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  ShieldQuestion,
  Ship,
  ShoppingCart,
  Sidebar,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  SquareCode,
  SquareTerminal,
  Sprout,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Tickets,
  Timer,
  Train,
  Trash2,
  Triangle,
  Trophy,
  Truck,
  Type,
  Tv,
  Umbrella,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Wallet,
  WandSparkles,
  Waypoints,
  Webcam,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  X,
  Youtube,
  Zap,
} from 'lucide-react';

export const commonLucideIconNames = [
  'Star', 'Heart', 'Bookmark', 'Flag', 'Tag', 'Hash', 'BadgeCheck', 'Crown',
  'Home', 'User', 'Users', 'Settings', 'Cog', 'Bell', 'BellRing', 'Mail',
  'Calendar', 'CalendarCheck', 'CalendarDays', 'Clock', 'Timer', 'AlarmClock',
  'MapPin', 'Map', 'MapPinned', 'Navigation', 'Route', 'Waypoints', 'Phone',
  'Camera', 'Image', 'Album', 'Film', 'Video', 'Tv', 'Webcam',
  'Folder', 'File', 'Archive', 'ArchiveRestore', 'Boxes', 'Inbox', 'Trash2', 'Download', 'Upload',
  'CloudDownload', 'CloudUpload', 'Clipboard', 'ClipboardCheck', 'ClipboardList', 'Notebook',
  'Search', 'Filter', 'Menu', 'MoreVertical', 'Ellipsis', 'ChevronDown', 'ChevronUp',
  'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowUpRight',
  'Plus', 'Minus', 'X', 'Check', 'AlertCircle', 'AlertTriangle', 'Info',
  'Edit', 'Copy', 'Share', 'Link', 'ExternalLink', 'Lock', 'Shield', 'ShieldCheck', 'ShieldQuestion',
  'Eye', 'EyeOff', 'Fingerprint', 'Scan', 'QrCode',
  'Code', 'Terminal', 'SquareCode', 'SquareTerminal', 'Database', 'Server', 'Cloud', 'Wifi',
  'Cpu', 'HardDrive', 'Monitor', 'Laptop', 'Smartphone', 'Tablet', 'MousePointer', 'Command',
  'Plug', 'Router', 'Bluetooth', 'Airplay', 'AppWindow', 'Workflow',
  'ShoppingCart', 'CreditCard', 'Package', 'Truck', 'Store', 'Receipt', 'Wallet', 'Banknote', 'DollarSign', 'Barcode',
  'Music', 'Play', 'Pause', 'Volume2', 'Headphones', 'Mic', 'Radio',
  'Book', 'BookOpen', 'FileText', 'Highlighter', 'Type', 'Languages', 'GraduationCap', 'School', 'Newspaper',
  'Layout', 'Grid', 'List', 'ListChecks', 'Columns', 'Sidebar', 'Layers', 'Blocks', 'Puzzle',
  'Circle', 'Square', 'Triangle', 'Hexagon', 'Diamond', 'Zap', 'Target', 'Sparkles', 'WandSparkles',
  'Rocket', 'Plane', 'Car', 'Bike', 'Ship', 'Train',
  'Moon', 'Sun', 'CloudRain', 'CloudSnow', 'Wind', 'Thermometer', 'Flame', 'Sprout', 'Flower', 'Umbrella',
  'Github', 'Gitlab', 'Chrome', 'Youtube', 'Apple', 'Figma',
  'MessageSquare', 'MessageCircle', 'Send', 'AtSign', 'Percent', 'Megaphone', 'Rss',
  'Palette', 'Brush', 'PenTool', 'Gamepad2', 'Bot', 'Compass', 'Globe', 'Earth',
  'Briefcase', 'Building', 'Building2', 'Landmark', 'Calculator', 'ChartBar', 'ChartLine', 'ChartPie', 'BarChart3',
  'Accessibility', 'Activity', 'Battery', 'Dumbbell', 'Gauge', 'Gift', 'Handshake', 'Laugh', 'Lightbulb',
  'Presentation', 'Projector', 'Tickets', 'Trophy', 'Wrench', 'Smile',
] as const;

const iconRegistry = {
  Accessibility,
  Activity,
  Airplay,
  AlarmClock,
  Album,
  AlertCircle,
  AlertTriangle,
  AppWindow,
  Apple,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  Banknote,
  Barcode,
  BarChart3,
  Battery,
  Bell,
  BellRing,
  Bike,
  Blocks,
  Bluetooth,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronUp,
  Chrome,
  Circle,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudRain,
  CloudSnow,
  CloudUpload,
  Code,
  Cog,
  Columns,
  Command,
  Compass,
  Copy,
  CreditCard,
  Cpu,
  Crown,
  Database,
  Diamond,
  DollarSign,
  Download,
  Dumbbell,
  Earth,
  Edit,
  Ellipsis,
  Eye,
  EyeOff,
  ExternalLink,
  Figma,
  File,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Folder,
  Gamepad2,
  Gauge,
  Github,
  Gitlab,
  Gift,
  Globe,
  GraduationCap,
  Grid,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Home,
  Image,
  Inbox,
  Info,
  Landmark,
  Languages,
  Layers,
  Layout,
  Laptop,
  Laugh,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  MousePointer,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Pause,
  Percent,
  PenTool,
  Phone,
  Plane,
  Play,
  Plug,
  Plus,
  Presentation,
  Projector,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  Rocket,
  RotateCcw,
  Route,
  Router,
  Rss,
  Scan,
  School,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  ShieldQuestion,
  Ship,
  ShoppingCart,
  Sidebar,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  SquareCode,
  SquareTerminal,
  Sprout,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Tickets,
  Timer,
  Train,
  Trash2,
  Triangle,
  Trophy,
  Truck,
  Type,
  Tv,
  Umbrella,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Wallet,
  WandSparkles,
  Waypoints,
  Webcam,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  X,
  Youtube,
  Zap,
} satisfies Record<string, LucideIcon>;

const kebabToPascal = (kebabName: string): string => {
  return kebabName
    .split('-')
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
};

export const normalizeLucideIconName = (rawName: string): keyof typeof iconRegistry | '' => {
  const name = rawName.trim();
  if (!name) return '';

  const candidates = [
    name,
    name.includes('-') ? kebabToPascal(name) : name,
    name.charAt(0).toUpperCase() + name.slice(1),
  ];

  for (const candidate of candidates) {
    if (candidate in iconRegistry) {
      return candidate as keyof typeof iconRegistry;
    }
  }

  return '';
};

export const resolveLucideIcon = (rawName: string): LucideIcon | null => {
  const normalizedName = normalizeLucideIconName(rawName);
  return normalizedName ? iconRegistry[normalizedName] : null;
};

export const fallbackIcon = Link;
